name: CI

on:
  # Trigger on push of tags
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get
      
      - name: Clean Flutter build
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Use ref_name to get the tag name without refs/
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
          
          draft: false
          prerelease: false
