on:
  push:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release 

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
         
          path: build/app/outputs/flutter-apk/app-release.apk
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}